- block:
  - name: Ensure docker daemon is started and enabled
    systemd:
      name: docker
      enabled: true
      state: 'started'
  when: component_type == 'worker'

# Copy required files
- name: Copy required files
  become: true
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "{{ '../../files/' + hostvars[inventory_hostname]['intermediate_certificate_name'] }}", dest: "/opt/beats/" }

- name: Copy Filebeat template file
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "filebeat.yml.j2", dest: "/opt/beats/filebeat-docker.yml" }
    - { src: "docker-compose.yml.j2", dest: "/opt/beats/docker-compose.yml" }

- name: Find Docker Compose version
  shell: docker compose version
  register: docker_compose_version
  ignore_errors: True

- block:
  - name: Start Filebeat
    community.docker.docker_compose:
      project_src: /opt/beats/
      state: present
      restarted: true
      debug: false
    register: output
  when: docker_compose_version is defined and (docker_compose_version|split(' ')|replace('v','')|float < 2.18.0 )

- block:
  - name: Start Filebeat
    community.docker.docker_compose_v2:
      project_src: /opt/beats/
      state: present
      build: always
    register: output
  when: docker_compose_version is defined and (docker_compose_version|split(' ')|replace('v','')|float >= 2.18.0 )

- name: Check if service is running
  ansible.builtin.assert:
    that:
      - "output.services.filebeat.fabric_beats_filebeat.state.running"

