# Some conifguration files are generated and saved in mf-parser repo.
# This task gets those needed files from the repo

- name: Clone mf-parser repo
  ansible.builtin.git:
    repo: >-
      {{ 'https://x-access-token:'+mf_parsers_github_access_token+'@github.com/fabric-testbed/mf-parsers.git' if mf_parsers_github_access_token is defined else 'git@github.com:fabric-testbed/mf-parsers.git' }}
    dest: "{{ tmp_deployment_files+'/mf-parsers' }}"
    single_branch: true
    version: main
    force: true
