---



############################
# Get Remote Write Configs #
############################

- name: Get Parsed Files 
  tags:
  - clone_mf_parsers
  import_tasks: get_mf_parser_files_tasks.yml
  delegate_to: 127.0.0.1
  when: component_type == 'head'



# OK
########################################
#  Fabric Rack Head Node Prometheus    #
########################################
- name: Head Node - Install Fabric-Prometheus setup 
  tags:
  - install_head_node
  block:
  - name: Install Fabric Rack
    import_tasks: fabric_rack_install_tasks.yml
    when: component_type == 'head'
  # when: 
  #   - install_type is defined
  #   - install_type == 'fabric_rack'


#
##############################
#  Fabric Rack Worker Node   #
##############################
- name: Worker Node - Install Fabric-Prometheus setup
  tags: install_worker_nodes
  block:
  - name: Install Fabric Rack
    import_tasks: fabric_worker_install_tasks.yml
    when: component_type == 'worker'


# OK
##############################
#  Node Exporter Install     #
##############################
- name: Install node_exporter 
  tags: install_node_exporters
  # need each node to have node_exporter
  block:
  - name: Install Node_exporter
    import_tasks: install_node_exporter_tasks.yml
    when: 
      - component_type == 'head' or component_type == 'worker'
  when: 
    - install_node_exporters is defined
    - install_node_exporters #== yes


# ##############################
# # Worker Node Docker System   #
# ##############################
# #docker - should be already there
# #docker network -need to add
# #nginx - need to add
# #docker monitor - need to add

# - name: Install worker node network and proxy nginx 
#   # need each worker node to have docker network and nginx 
#   # to proxy things without TLS or auth
#   block:
#   - name: Install worker docker network
#     import_tasks: worker_node_tasks.yml
#     when: 
#       component_type == 'worker'
#   when: 
#     - install_type is defined
#     - install_type == 'fabric_rack' 


# OK
##############################
# Setup VPN Ping Configs     #
##############################
- name: Setup VPN configs 
  tags: install_head_node
  block:
  - name: Setup Promtheus Config Files
    include_tasks: Prometheus/add_prometheus_config_templates.yml
    # Just copies the one template to the Promtheus config.
    # Note assumes the prometheus_templates_dir has been set in vars file.
    vars:
      prometheus_config_template_files:
        - vpn_ping_targets.yml
  when: 
    # - install_type is defined
    # - install_type == 'fabric_rack' 
    - component_type == 'head'
    - set_vpn_pings is defined
    - set_vpn_pings #== yes

#############
# Cant do - will slow down every deploymente
# WILL WIPE OUT EDITED var & hosts files!!!
# - name: Clean up tmp_deployment_files 
#   file:
#     path: "{{ tmp_deployment_files }}"
#     state: absent
#   delegate_to: 127.0.0.1
#   when: component_type == 'head'